play:
  fields:
    url:
      required: true
      selector:
        text:
          type: url
    media_player:
      required: true
      selector:
        entity:
          domain: media_player
          multiple: false
