search:
  fields:
    query:
      required: true
      selector:
        text:
    limit:
      default: 10
      selector:
        number:
          min: 1
          max: 50
          step: 1
          mode: box

play:
  fields:
    url:
      required: true
      selector:
        text:
          type: url
    media_player:
      required: true
      selector:
        entity:
          domain: media_player
          multiple: false

play_multi:
  fields:
    url:
      required: true
      selector:
        text:
          type: url
    media_players:
      required: true
      selector:
        entity:
          multiple: true
          filter:
            domain: media_player

scan_library:
  fields:
    force:
      default: false
      selector:
        boolean:

favorites_list:
  fields: {}

favorites_add:
  fields:
    url:
      required: true
      selector:
        text:
          type: url

favorites_remove:
  fields:
    url:
      required: true
      selector:
        text:
          type: url

favorites_playback_get:
  fields: {}

favorites_playback_set:
  fields:
    online_selected:
      required: true
      selector:
        object:
    offline_selected:
      required: true
      selector:
        object:
    repeat_mode:
      required: true
      selector:
        select:
          options:
            - "off"
            - "one"
            - "all"

favorites_playback_start:
  fields:
    kind:
      required: true
      selector:
        select:
          options:
            - online
            - offline
    queue:
      required: true
      selector:
        object:
    media_players:
      required: true
      selector:
        entity:
          multiple: true
          filter:
            domain: media_player
    repeat_mode:
      required: true
      selector:
        select:
          options:
            - "off"
            - "one"
            - "all"
    replace_selection:
      default: true
      selector:
        boolean:

favorites_playback_skip:
  fields:
    direction:
      required: true
      selector:
        select:
          options:
            - previous
            - next
            - current

favorites_playback_stop:
  fields: {}

get_media_targets:
  fields: {}

play_targets:
  fields:
    url:
      required: true
      selector:
        text:
          type: url
    media_players:
      required: true
      selector:
        entity:
          multiple: true
          filter:
            domain: media_player
